### ISSUE TITLE
Is there a way to read more than one line?

### ISSUE THREAD

**Issue by BrokenEncoder** [ThomasRooney/gexpect#24]
Is there a easy way to read more that one line from the output  ? 

In the python version you can use the following to grab the whole buffer: 

child.before 

I'm looking for something similar. 

or  a way to search the buffer for a string and read it and everything else on the line .

**Comment by ThomasRooney** [comment]
For a `child.before` equivalent,  use `Capture()` at process spawn to start saving process output into a buffer. When desired (e.g. after an `Expect()` call has completed), you can call `Collect()` to get a byte array with all process output up until that point.

If you're just looking for a particular string in a line, and want to get the rest of that line then use `ExpectRegexFind`.

    child := gexpect.Spawn("echo 123 456 789")
    result, _ := child.ExpectRegexFind("\d+ (\d+) (\d+)")
    // result = []string{"123 456 789", "456", "789"}
