### ISSUE TITLE
Interact looks racy

### ISSUE THREAD

**Issue by krnowak** [ThomasRooney/gexpect#7]
Interact tries to copy everything from PTY to both standard output and standard error in two goroutines. Isn't that racy? Sometimes contents of PTY will end up in standard output, sometimes in standard error.

Not sure what should be the fix - either remove the `go io.Copy(os.Stderr, expect.f)` line or something like:
```go
go func() {
	mw := io.MultiWriter(os.Stdout, os.Stderr)
	io.Copy(mw, expect.f)
}()
```
I suppose the former.

**Comment by ThomasRooney** [comment]
You're right -- it makes zero sense to do this:

	io.Copy(os.Stdout, &expect.buf.b)
	go io.Copy(os.Stdout, expect.buf.f)
	go io.Copy(os.Stderr, expect.buf.f)
	go io.Copy(expect.buf.f, os.Stdin)

I wrote that with a misunderstanding of how virtual terminals work.

After a little research, underlying this all is the special os.File ("/dev/ptmx") with no separation between stdout and stderr streams (for mac/linux, BSD works differently). One option is to play with pty directly, i.e. https://code.google.com/p/lilykde/source/browse/trunk/runpty.py?r=314. However then there would be  cross platform complexities. Another option is separating stdout and stderr by enforcing a redirection to a FIFO queue, with something like `mkfifo /tmp/pipe_01` and `2>&/tmp/pipe_01`. However making this play nicely with a generic "give me a command, and I'll run it" ideal would be difficult -- this would break people's subprocesses when they're manipulating the stdout and stderr pipes themselves.

It's probably unnecessary, I can't think of much process interaction where one would want separate stdout and stderr queues.

I think the simplest option is to just remove the `go io.Copy(os.Stderr, expect.buf.f)`. Thanks for pointing this out.
