### ISSUE TITLE
TestBiChannel failure

### ISSUE THREAD

**Issue by dgoeke** [ThomasRooney/gexpect#9]
Using the current master of gexpect with Ubuntu 14.04 and Go 1.4.2 linux/amd64, running "go test -v" hangs inside TestBiChannel:

    === RUN TestHelloWorld
    --- PASS: TestHelloWorld (0.00s)
            gexpect_test.go:10: Testing Hello World...
    === RUN TestDoubleHelloWorld
    --- PASS: TestDoubleHelloWorld (0.00s)
            gexpect_test.go:22: Testing Double Hello World...
    === RUN TestHelloWorldFailureCase
    --- PASS: TestHelloWorldFailureCase (0.00s)
            gexpect_test.go:42: Testing Hello World Failure case...
    === RUN TestBiChannel
    (...never completes...)

Debugging a little, it seems that the "msg" variable at gexpect_test:62 gets the original "echo" twice and waiting for "echo2" never completes.

**Comment by ThomasRooney** [comment]
Sadly these tests are a little tied to the execution environment in which the library is run under. I.e. it works for me. Would you mind seeing if the change
	sender <- "echo2"
	wait("echo2")
	child.Close()
to 
	sender <- "echo2\n"
	wait("echo2")
	child.Close()

Makes any difference?

**Comment by dgoeke** [comment]
Adding a newline does solve the test hang.  The original echo still gets processed twice, but that doesn't seem to matter.

**Comment by steveeJ** [comment]
Since this hasn't been fixed yet I assume that adding the `\n` isn't a proper solution here. I'm curious: why? I'd guess that on other platforms a line wouldn't necessarily end on `\n`, but I'd rather know than guess :-)
